### ISSUE TITLE
Authenticate.php Error When Trying To Change Password

### ISSUE THREAD

**Issue by RuMoR0922** [circlestorm/Sakura#8]
This Issue Arises When You Try To Change Your Password

Here's A Screenshot!
![Image Of Issue](http://i.imgur.com/uBeXnvJ.png)

**Comment by flashwave** [comment]
i'm going to destroy

**Comment by flashwave** [comment]
once again, destroy you

**Comment by flashwave** [comment]
destruction will be among us soon

**Comment by RuMoR0922** [comment]
ripperino

**Comment by flashwave** [comment]
Was a DOM issue.
